No local.py imported, skipping.
/opt/rh/python27/root/usr/lib/python2.7/site-packages/django_statsd/patches/__init__.py:2: RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.
  from django.utils.importlib import import_module

No local.py imported, skipping.
/opt/rh/python27/root/usr/lib/python2.7/site-packages/django_statsd/patches/__init__.py:2: RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.
  from django.utils.importlib import import_module

Performing system checks...

System check identified no issues (0 silenced).
May 14, 2015 - 22:29:15
Django version 1.8.1, using settings 'auth.settings'
Starting development server at http://0.0.0.0:2603/
Quit the server with CONTROL-C.
No local.py imported, skipping.
/opt/rh/python27/root/usr/lib/python2.7/site-packages/django_statsd/patches/__init__.py:2: RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.
  from django.utils.importlib import import_module

No local.py imported, skipping.
/opt/rh/python27/root/usr/lib/python2.7/site-packages/django_statsd/patches/__init__.py:2: RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.
  from django.utils.importlib import import_module

Performing system checks...

System check identified no issues (0 silenced).
May 14, 2015 - 22:30:04
Django version 1.8.1, using settings 'auth.settings'
Starting development server at http://0.0.0.0:2603/
Quit the server with CONTROL-C.
No local.py imported, skipping.
/opt/rh/python27/root/usr/lib/python2.7/site-packages/django_statsd/patches/__init__.py:2: RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.
  from django.utils.importlib import import_module

No local.py imported, skipping.
/opt/rh/python27/root/usr/lib/python2.7/site-packages/django_statsd/patches/__init__.py:2: RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.
  from django.utils.importlib import import_module

Performing system checks...

System check identified no issues (0 silenced).
May 14, 2015 - 22:41:20
Django version 1.8.1, using settings 'auth.settings'
Starting development server at http://0.0.0.0:2603/
Quit the server with CONTROL-C.
No local.py imported, skipping.
/opt/rh/python27/root/usr/lib/python2.7/site-packages/django_statsd/patches/__init__.py:2: RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.
  from django.utils.importlib import import_module

No local.py imported, skipping.
/opt/rh/python27/root/usr/lib/python2.7/site-packages/django_statsd/patches/__init__.py:2: RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.
  from django.utils.importlib import import_module

Performing system checks...

System check identified no issues (0 silenced).
May 15, 2015 - 03:22:01
Django version 1.8.1, using settings 'auth.settings'
Starting development server at http://0.0.0.0:2603/
Quit the server with CONTROL-C.
No local.py imported, skipping.
/opt/rh/python27/root/usr/lib/python2.7/site-packages/django_statsd/patches/__init__.py:2: RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.
  from django.utils.importlib import import_module

Performing system checks...

System check identified no issues (0 silenced).
May 15, 2015 - 03:47:45
Django version 1.8.1, using settings 'auth.settings'
Starting development server at http://0.0.0.0:2603/
Quit the server with CONTROL-C.
No local.py imported, skipping.
/opt/rh/python27/root/usr/lib/python2.7/site-packages/django_statsd/patches/__init__.py:2: RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.
  from django.utils.importlib import import_module

Performing system checks...

System check identified no issues (0 silenced).
May 15, 2015 - 03:47:46
Django version 1.8.1, using settings 'auth.settings'
Starting development server at http://0.0.0.0:2603/
Quit the server with CONTROL-C.
No local.py imported, skipping.
/opt/rh/python27/root/usr/lib/python2.7/site-packages/django_statsd/patches/__init__.py:2: RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.
  from django.utils.importlib import import_module

Performing system checks...

System check identified no issues (0 silenced).
May 15, 2015 - 03:48:18
Django version 1.8.1, using settings 'auth.settings'
Starting development server at http://0.0.0.0:2603/
Quit the server with CONTROL-C.
No local.py imported, skipping.
/opt/rh/python27/root/usr/lib/python2.7/site-packages/django_statsd/patches/__init__.py:2: RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.
  from django.utils.importlib import import_module

Performing system checks...

System check identified no issues (0 silenced).
May 15, 2015 - 03:49:39
Django version 1.8.1, using settings 'auth.settings'
Starting development server at http://0.0.0.0:2603/
Quit the server with CONTROL-C.
No local.py imported, skipping.
/opt/rh/python27/root/usr/lib/python2.7/site-packages/django_statsd/patches/__init__.py:2: RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.
  from django.utils.importlib import import_module

Performing system checks...

System check identified no issues (0 silenced).
May 15, 2015 - 03:49:48
Django version 1.8.1, using settings 'auth.settings'
Starting development server at http://0.0.0.0:2603/
Quit the server with CONTROL-C.
No local.py imported, skipping.
/opt/rh/python27/root/usr/lib/python2.7/site-packages/django_statsd/patches/__init__.py:2: RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.
  from django.utils.importlib import import_module

No local.py imported, skipping.
/opt/rh/python27/root/usr/lib/python2.7/site-packages/django_statsd/patches/__init__.py:2: RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.
  from django.utils.importlib import import_module

Performing system checks...

System check identified no issues (0 silenced).
May 15, 2015 - 04:28:52
Django version 1.8.1, using settings 'auth.settings'
Starting development server at http://0.0.0.0:2603/
Quit the server with CONTROL-C.
No local.py imported, skipping.
/opt/rh/python27/root/usr/lib/python2.7/site-packages/django_statsd/patches/__init__.py:2: RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.
  from django.utils.importlib import import_module

No local.py imported, skipping.
/opt/rh/python27/root/usr/lib/python2.7/site-packages/django_statsd/patches/__init__.py:2: RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.
  from django.utils.importlib import import_module

Performing system checks...

System check identified no issues (0 silenced).
May 15, 2015 - 04:28:58
Django version 1.8.1, using settings 'auth.settings'
Starting development server at http://0.0.0.0:2603/
Quit the server with CONTROL-C.
No local.py imported, skipping.
/opt/rh/python27/root/usr/lib/python2.7/site-packages/django_statsd/patches/__init__.py:2: RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.
  from django.utils.importlib import import_module

No local.py imported, skipping.
/opt/rh/python27/root/usr/lib/python2.7/site-packages/django_statsd/patches/__init__.py:2: RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.
  from django.utils.importlib import import_module

Performing system checks...

System check identified no issues (0 silenced).
May 15, 2015 - 16:30:23
Django version 1.8.1, using settings 'auth.settings'
Starting development server at http://0.0.0.0:2603/
Quit the server with CONTROL-C.
No local.py imported, skipping.
/opt/rh/python27/root/usr/lib/python2.7/site-packages/django_statsd/patches/__init__.py:2: RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.
  from django.utils.importlib import import_module

No local.py imported, skipping.
/opt/rh/python27/root/usr/lib/python2.7/site-packages/django_statsd/patches/__init__.py:2: RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.
  from django.utils.importlib import import_module

Performing system checks...

System check identified no issues (0 silenced).
May 15, 2015 - 16:56:06
Django version 1.8.1, using settings 'auth.settings'
Starting development server at http://0.0.0.0:2603/
Quit the server with CONTROL-C.
No local.py imported, skipping.
/opt/rh/python27/root/usr/lib/python2.7/site-packages/django_statsd/patches/__init__.py:2: RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.
  from django.utils.importlib import import_module

No local.py imported, skipping.
/opt/rh/python27/root/usr/lib/python2.7/site-packages/django_statsd/patches/__init__.py:2: RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.
  from django.utils.importlib import import_module

Performing system checks...

System check identified no issues (0 silenced).
May 15, 2015 - 16:58:04
Django version 1.8.1, using settings 'auth.settings'
Starting development server at http://0.0.0.0:2603/
Quit the server with CONTROL-C.
No local.py imported, skipping.
/opt/rh/python27/root/usr/lib/python2.7/site-packages/django_statsd/patches/__init__.py:2: RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.
  from django.utils.importlib import import_module

No local.py imported, skipping.
/opt/rh/python27/root/usr/lib/python2.7/site-packages/django_statsd/patches/__init__.py:2: RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.
  from django.utils.importlib import import_module

Performing system checks...

System check identified no issues (0 silenced).
May 15, 2015 - 17:01:33
Django version 1.8.1, using settings 'auth.settings'
Starting development server at http://0.0.0.0:2603/
Quit the server with CONTROL-C.
No local.py imported, skipping.
/opt/rh/python27/root/usr/lib/python2.7/site-packages/django_statsd/patches/__init__.py:2: RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.
  from django.utils.importlib import import_module

No local.py imported, skipping.
/opt/rh/python27/root/usr/lib/python2.7/site-packages/django_statsd/patches/__init__.py:2: RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.
  from django.utils.importlib import import_module

Performing system checks...

System check identified no issues (0 silenced).
May 15, 2015 - 17:06:58
Django version 1.8.1, using settings 'auth.settings'
Starting development server at http://0.0.0.0:2603/
Quit the server with CONTROL-C.
No local.py imported, skipping.
/opt/rh/python27/root/usr/lib/python2.7/site-packages/django_statsd/patches/__init__.py:2: RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.
  from django.utils.importlib import import_module

No local.py imported, skipping.
/opt/rh/python27/root/usr/lib/python2.7/site-packages/django_statsd/patches/__init__.py:2: RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.
  from django.utils.importlib import import_module

Performing system checks...

System check identified no issues (0 silenced).
May 15, 2015 - 17:11:33
Django version 1.8.1, using settings 'auth.settings'
Starting development server at http://0.0.0.0:2603/
Quit the server with CONTROL-C.
No local.py imported, skipping.
/opt/rh/python27/root/usr/lib/python2.7/site-packages/django_statsd/patches/__init__.py:2: RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.
  from django.utils.importlib import import_module

No local.py imported, skipping.
/opt/rh/python27/root/usr/lib/python2.7/site-packages/django_statsd/patches/__init__.py:2: RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.
  from django.utils.importlib import import_module

Performing system checks...

System check identified no issues (0 silenced).
May 16, 2015 - 03:06:08
Django version 1.8.1, using settings 'auth.settings'
Starting development server at http://0.0.0.0:2603/
Quit the server with CONTROL-C.
No local.py imported, skipping.
/opt/rh/python27/root/usr/lib/python2.7/site-packages/django_statsd/patches/__init__.py:2: RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.
  from django.utils.importlib import import_module

No local.py imported, skipping.
/opt/rh/python27/root/usr/lib/python2.7/site-packages/django_statsd/patches/__init__.py:2: RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.
  from django.utils.importlib import import_module

Performing system checks...

System check identified no issues (0 silenced).
May 16, 2015 - 03:06:27
Django version 1.8.1, using settings 'auth.settings'
Starting development server at http://0.0.0.0:2603/
Quit the server with CONTROL-C.
No local.py imported, skipping.
No local.py imported, skipping.
Performing system checks...

System check identified no issues (0 silenced).
CREATE TABLE "django_migrations" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "app" varchar(255) NOT NULL, "name" varchar(255) NOT NULL, "applied" datetime NOT NULL); (params None)
June 02, 2015 - 18:39:35
Django version 1.8.1, using settings 'auth.settings'
Starting development server at http://0.0.0.0:2603/
Quit the server with CONTROL-C.
No local.py imported, skipping.
No local.py imported, skipping.
Performing system checks...

System check identified no issues (0 silenced).
CREATE TABLE "django_migrations" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "app" varchar(255) NOT NULL, "name" varchar(255) NOT NULL, "applied" datetime NOT NULL); (params None)
June 02, 2015 - 20:18:34
Django version 1.8.1, using settings 'auth.settings'
Starting development server at http://0.0.0.0:2603/
Quit the server with CONTROL-C.
No local.py imported, skipping.
No local.py imported, skipping.
Performing system checks...

System check identified no issues (0 silenced).
CREATE TABLE "django_migrations" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "app" varchar(255) NOT NULL, "name" varchar(255) NOT NULL, "applied" datetime NOT NULL); (params None)
June 02, 2015 - 20:18:52
Django version 1.8.1, using settings 'auth.settings'
Starting development server at http://0.0.0.0:2603/
Quit the server with CONTROL-C.
No local.py imported, skipping.
No local.py imported, skipping.
Performing system checks...

System check identified no issues (0 silenced).
CREATE TABLE "django_migrations" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "app" varchar(255) NOT NULL, "name" varchar(255) NOT NULL, "applied" datetime NOT NULL); (params None)
June 02, 2015 - 20:41:09
Django version 1.8.1, using settings 'auth.settings'
Starting development server at http://0.0.0.0:2603/
Quit the server with CONTROL-C.
No local.py imported, skipping.
No local.py imported, skipping.
Performing system checks...

System check identified no issues (0 silenced).
CREATE TABLE "django_migrations" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "app" varchar(255) NOT NULL, "name" varchar(255) NOT NULL, "applied" datetime NOT NULL); (params None)
June 02, 2015 - 20:42:37
Django version 1.8.1, using settings 'auth.settings'
Starting development server at http://0.0.0.0:2603/
Quit the server with CONTROL-C.
No local.py imported, skipping.
No local.py imported, skipping.
Performing system checks...

System check identified no issues (0 silenced).
CREATE TABLE "django_migrations" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "app" varchar(255) NOT NULL, "name" varchar(255) NOT NULL, "applied" datetime NOT NULL); (params None)
June 02, 2015 - 20:46:49
Django version 1.8.1, using settings 'auth.settings'
Starting development server at http://0.0.0.0:2603/
Quit the server with CONTROL-C.
No local.py imported, skipping.
No local.py imported, skipping.
Performing system checks...

System check identified no issues (0 silenced).
CREATE TABLE "django_migrations" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "app" varchar(255) NOT NULL, "name" varchar(255) NOT NULL, "applied" datetime NOT NULL); (params None)
June 02, 2015 - 21:04:07
Django version 1.8.1, using settings 'auth.settings'
Starting development server at http://0.0.0.0:2603/
Quit the server with CONTROL-C.
No local.py imported, skipping.
No local.py imported, skipping.
Performing system checks...

System check identified no issues (0 silenced).
CREATE TABLE "django_migrations" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "app" varchar(255) NOT NULL, "name" varchar(255) NOT NULL, "applied" datetime NOT NULL); (params None)
June 02, 2015 - 21:07:12
Django version 1.8.1, using settings 'auth.settings'
Starting development server at http://0.0.0.0:2603/
Quit the server with CONTROL-C.
No local.py imported, skipping.
No local.py imported, skipping.
Performing system checks...

System check identified no issues (0 silenced).
CREATE TABLE "django_migrations" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "app" varchar(255) NOT NULL, "name" varchar(255) NOT NULL, "applied" datetime NOT NULL); (params None)
June 03, 2015 - 03:47:29
Django version 1.8.1, using settings 'auth.settings'
Starting development server at http://0.0.0.0:2603/
Quit the server with CONTROL-C.
Client did not specify the provider URL in the headers.
[03/Jun/2015 03:57:23]"POST /v1/braintree HTTP/1.1" 422 0
[03/Jun/2015 03:58:16]"POST /v1/braintree/ HTTP/1.1" 404 2226
Client did not specify the provider URL in the headers.
[03/Jun/2015 03:58:42]"POST /v1/braintree HTTP/1.1" 422 0
Client did not specify the provider URL in the headers.
[03/Jun/2015 03:59:14]"POST /v1/braintree HTTP/1.1" 422 0
Processing request for: https://api.sandbox.braintreegateway.com:443/merchants/tbb7hb44zx28jhsh/customers/advanced_search_ids
Adding header: Content-Type, application/xml
Adding header: HTTP-X-ApiVersion, 4
[03/Jun/2015 04:00:23]"POST /v1/braintree HTTP/1.1" 500 57225
No local.py imported, skipping.
Performing system checks...

System check identified no issues (0 silenced).
CREATE TABLE "django_migrations" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "app" varchar(255) NOT NULL, "name" varchar(255) NOT NULL, "applied" datetime NOT NULL); (params None)
June 03, 2015 - 04:01:31
Django version 1.8.1, using settings 'auth.settings'
Starting development server at http://0.0.0.0:2603/
Quit the server with CONTROL-C.
Processing request for: https://api.sandbox.braintreegateway.com:443/merchants/tbb7hb44zx28jhsh/customers/advanced_search_ids
Adding header: Content-Type, application/xml
Adding header: HTTP-X-ApiVersion, 4
[03/Jun/2015 04:01:57]"POST /v1/braintree HTTP/1.1" 500 57225
No local.py imported, skipping.
Performing system checks...

System check identified no issues (0 silenced).
CREATE TABLE "django_migrations" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "app" varchar(255) NOT NULL, "name" varchar(255) NOT NULL, "applied" datetime NOT NULL); (params None)
June 03, 2015 - 04:02:06
Django version 1.8.1, using settings 'auth.settings'
Starting development server at http://0.0.0.0:2603/
Quit the server with CONTROL-C.
Processing request for: https://api.sandbox.braintreegateway.com:443/merchants/tbb7hb44zx28jhsh/customers/advanced_search_ids
Adding header: Content-Type, application/xml
Adding header: HTTP-X-ApiVersion, 4
[03/Jun/2015 04:02:08]"POST /v1/braintree HTTP/1.1" 500 57225
No local.py imported, skipping.
Performing system checks...

System check identified no issues (0 silenced).
CREATE TABLE "django_migrations" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "app" varchar(255) NOT NULL, "name" varchar(255) NOT NULL, "applied" datetime NOT NULL); (params None)
June 03, 2015 - 04:02:20
Django version 1.8.1, using settings 'auth.settings'
Starting development server at http://0.0.0.0:2603/
Quit the server with CONTROL-C.
Processing request for: https://api.sandbox.braintreegateway.com:443/merchants/tbb7hb44zx28jhsh/customers/advanced_search_ids
Adding header: Content-Type, application/xml
Adding header: HTTP-X-ApiVersion, 4
here!
[03/Jun/2015 04:02:21]"POST /v1/braintree HTTP/1.1" 500 57250
No local.py imported, skipping.
Performing system checks...

System check identified no issues (0 silenced).
CREATE TABLE "django_migrations" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "app" varchar(255) NOT NULL, "name" varchar(255) NOT NULL, "applied" datetime NOT NULL); (params None)
June 03, 2015 - 04:02:28
Django version 1.8.1, using settings 'auth.settings'
Starting development server at http://0.0.0.0:2603/
Quit the server with CONTROL-C.
Processing request for: https://api.sandbox.braintreegateway.com:443/merchants/tbb7hb44zx28jhsh/customers/advanced_search_ids
Adding header: Content-Type, application/xml
Adding header: HTTP-X-ApiVersion, 4
here!
[03/Jun/2015 04:02:29]"POST /v1/braintree HTTP/1.1" 500 57275
No local.py imported, skipping.
Performing system checks...

System check identified no issues (0 silenced).
CREATE TABLE "django_migrations" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "app" varchar(255) NOT NULL, "name" varchar(255) NOT NULL, "applied" datetime NOT NULL); (params None)
June 03, 2015 - 04:02:33
Django version 1.8.1, using settings 'auth.settings'
Starting development server at http://0.0.0.0:2603/
Quit the server with CONTROL-C.
Processing request for: https://api.sandbox.braintreegateway.com:443/merchants/tbb7hb44zx28jhsh/customers/advanced_search_ids
Adding header: Content-Type, application/xml
Adding header: HTTP-X-ApiVersion, 4
here!
None
54b479bd09f312dc448375b1b3fe94d8
[03/Jun/2015 04:02:45]"POST /v1/braintree HTTP/1.1" 500 57236
No local.py imported, skipping.
Performing system checks...

System check identified no issues (0 silenced).
CREATE TABLE "django_migrations" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "app" varchar(255) NOT NULL, "name" varchar(255) NOT NULL, "applied" datetime NOT NULL); (params None)
June 03, 2015 - 04:14:58
Django version 1.8.1, using settings 'auth.settings'
Starting development server at http://0.0.0.0:2603/
Quit the server with CONTROL-C.
Processing request for: https://api.sandbox.braintreegateway.com:443/merchants/tbb7hb44zx28jhsh/customers/advanced_search_ids
Adding header: Content-Type, application/xml
Adding header: HTTP-X-ApiVersion, 4
here!
r7ms2hhp9pnz8srd
54b479bd09f312dc448375b1b3fe94d8
there!
here!
61
Calling: https://api.sandbox.braintreegateway.com:443/merchants/tbb7hb44zx28jhsh/customers/advanced_search_ids
[03/Jun/2015 04:15:07]"POST /v1/braintree HTTP/1.1" 200 2025
No local.py imported, skipping.
Performing system checks...

System check identified no issues (0 silenced).
CREATE TABLE "django_migrations" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "app" varchar(255) NOT NULL, "name" varchar(255) NOT NULL, "applied" datetime NOT NULL); (params None)
June 03, 2015 - 04:15:53
Django version 1.8.1, using settings 'auth.settings'
Starting development server at http://0.0.0.0:2603/
Quit the server with CONTROL-C.
No local.py imported, skipping.
/opt/rh/python27/root/usr/lib/python2.7/site-packages/django_statsd/patches/__init__.py:2: RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.
  from django.utils.importlib import import_module

Performing system checks...

System check identified no issues (0 silenced).
June 03, 2015 - 04:41:43
Django version 1.8.1, using settings 'auth.settings'
Starting development server at http://0.0.0.0:2603/
Quit the server with CONTROL-C.
Traceback (most recent call last):
  File "/srv/auth/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 303, in execute
    settings.INSTALLED_APPS
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/django/conf/__init__.py", line 48, in __getattr__
    self._setup(name)
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/django/conf/__init__.py", line 44, in _setup
    self._wrapped = Settings(settings_module)
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/django/conf/__init__.py", line 92, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/opt/rh/python27/root/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/srv/auth/auth/settings/__init__.py", line 1, in <module>
    from .base import *  # noqa
  File "/srv/auth/auth/settings/base.py", line 98
    <<<<<<< HEAD
     ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/srv/auth/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 303, in execute
    settings.INSTALLED_APPS
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/django/conf/__init__.py", line 48, in __getattr__
    self._setup(name)
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/django/conf/__init__.py", line 44, in _setup
    self._wrapped = Settings(settings_module)
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/django/conf/__init__.py", line 92, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/opt/rh/python27/root/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/srv/auth/auth/settings/__init__.py", line 1, in <module>
    from .base import *  # noqa
  File "/srv/auth/auth/settings/base.py", line 98
    <<<<<<< HEAD
     ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/srv/auth/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 303, in execute
    settings.INSTALLED_APPS
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/django/conf/__init__.py", line 48, in __getattr__
    self._setup(name)
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/django/conf/__init__.py", line 44, in _setup
    self._wrapped = Settings(settings_module)
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/django/conf/__init__.py", line 92, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/opt/rh/python27/root/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/srv/auth/auth/settings/__init__.py", line 1, in <module>
    from .base import *  # noqa
  File "/srv/auth/auth/settings/base.py", line 98
    <<<<<<< HEAD
     ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/srv/auth/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 303, in execute
    settings.INSTALLED_APPS
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/django/conf/__init__.py", line 48, in __getattr__
    self._setup(name)
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/django/conf/__init__.py", line 44, in _setup
    self._wrapped = Settings(settings_module)
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/django/conf/__init__.py", line 92, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/opt/rh/python27/root/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/srv/auth/auth/settings/__init__.py", line 1, in <module>
    from .base import *  # noqa
  File "/srv/auth/auth/settings/base.py", line 98
    <<<<<<< HEAD
     ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/srv/auth/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 303, in execute
    settings.INSTALLED_APPS
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/django/conf/__init__.py", line 48, in __getattr__
    self._setup(name)
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/django/conf/__init__.py", line 44, in _setup
    self._wrapped = Settings(settings_module)
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/django/conf/__init__.py", line 92, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/opt/rh/python27/root/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/srv/auth/auth/settings/__init__.py", line 1, in <module>
    from .base import *  # noqa
  File "/srv/auth/auth/settings/base.py", line 98
    <<<<<<< HEAD
     ^
SyntaxError: invalid syntax
No local.py imported, skipping.
/opt/rh/python27/root/usr/lib/python2.7/site-packages/django_statsd/patches/__init__.py:2: RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.
  from django.utils.importlib import import_module

No local.py imported, skipping.
/opt/rh/python27/root/usr/lib/python2.7/site-packages/django_statsd/patches/__init__.py:2: RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.
  from django.utils.importlib import import_module

Performing system checks...

System check identified no issues (0 silenced).
June 03, 2015 - 05:20:51
Django version 1.8.1, using settings 'auth.settings'
Starting development server at http://0.0.0.0:2603/
Quit the server with CONTROL-C.
[03/Jun/2015 05:21:22]"POST /v1/braintree HTTP/1.1" 201 1381
No local.py imported, skipping.
/opt/rh/python27/root/usr/lib/python2.7/site-packages/django_statsd/patches/__init__.py:2: RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.
  from django.utils.importlib import import_module

Performing system checks...

System check identified no issues (0 silenced).
June 03, 2015 - 05:22:30
Django version 1.8.1, using settings 'auth.settings'
Starting development server at http://0.0.0.0:2603/
Quit the server with CONTROL-C.
[03/Jun/2015 05:30:21]"POST /v1/braintree HTTP/1.1" 201 1381
No local.py imported, skipping.
/opt/rh/python27/root/usr/lib/python2.7/site-packages/django_statsd/patches/__init__.py:2: RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.
  from django.utils.importlib import import_module

Performing system checks...

System check identified no issues (0 silenced).
June 03, 2015 - 05:38:58
Django version 1.8.1, using settings 'auth.settings'
Starting development server at http://0.0.0.0:2603/
Quit the server with CONTROL-C.
No local.py imported, skipping.
/opt/rh/python27/root/usr/lib/python2.7/site-packages/django_statsd/patches/__init__.py:2: RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.
  from django.utils.importlib import import_module

No local.py imported, skipping.
/opt/rh/python27/root/usr/lib/python2.7/site-packages/django_statsd/patches/__init__.py:2: RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.
  from django.utils.importlib import import_module

Performing system checks...

System check identified no issues (0 silenced).
June 03, 2015 - 05:42:21
Django version 1.8.1, using settings 'auth.settings'
Starting development server at http://0.0.0.0:2603/
Quit the server with CONTROL-C.
No local.py imported, skipping.
/opt/rh/python27/root/usr/lib/python2.7/site-packages/django_statsd/patches/__init__.py:2: RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.
  from django.utils.importlib import import_module

No local.py imported, skipping.
/opt/rh/python27/root/usr/lib/python2.7/site-packages/django_statsd/patches/__init__.py:2: RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.
  from django.utils.importlib import import_module

Performing system checks...

System check identified no issues (0 silenced).
June 03, 2015 - 05:49:00
Django version 1.8.1, using settings 'auth.settings'
Starting development server at http://0.0.0.0:2603/
Quit the server with CONTROL-C.
No local.py imported, skipping.
/opt/rh/python27/root/usr/lib/python2.7/site-packages/django_statsd/patches/__init__.py:2: RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.
  from django.utils.importlib import import_module

No local.py imported, skipping.
/opt/rh/python27/root/usr/lib/python2.7/site-packages/django_statsd/patches/__init__.py:2: RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.
  from django.utils.importlib import import_module

Performing system checks...

System check identified no issues (0 silenced).
June 04, 2015 - 18:01:52
Django version 1.8.1, using settings 'auth.settings'
Starting development server at http://0.0.0.0:2603/
Quit the server with CONTROL-C.
No local.py imported, skipping.
/opt/rh/python27/root/usr/lib/python2.7/site-packages/django_statsd/patches/__init__.py:2: RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.
  from django.utils.importlib import import_module

Performing system checks...

System check identified no issues (0 silenced).
June 04, 2015 - 19:27:44
Django version 1.8.1, using settings 'auth.settings'
Starting development server at http://0.0.0.0:2603/
Quit the server with CONTROL-C.
No local.py imported, skipping.
/opt/rh/python27/root/usr/lib/python2.7/site-packages/django_statsd/patches/__init__.py:2: RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.
  from django.utils.importlib import import_module

Performing system checks...

System check identified no issues (0 silenced).
June 04, 2015 - 19:29:30
Django version 1.8.1, using settings 'auth.settings'
Starting development server at http://0.0.0.0:2603/
Quit the server with CONTROL-C.
No local.py imported, skipping.
/opt/rh/python27/root/usr/lib/python2.7/site-packages/django_statsd/patches/__init__.py:2: RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.
  from django.utils.importlib import import_module

Performing system checks...

System check identified no issues (0 silenced).
June 04, 2015 - 19:29:34
Django version 1.8.1, using settings 'auth.settings'
Starting development server at http://0.0.0.0:2603/
Quit the server with CONTROL-C.
No local.py imported, skipping.
/opt/rh/python27/root/usr/lib/python2.7/site-packages/django_statsd/patches/__init__.py:2: RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.
  from django.utils.importlib import import_module

Performing system checks...

System check identified no issues (0 silenced).
June 04, 2015 - 19:30:07
Django version 1.8.1, using settings 'auth.settings'
Starting development server at http://0.0.0.0:2603/
Quit the server with CONTROL-C.
No local.py imported, skipping.
/opt/rh/python27/root/usr/lib/python2.7/site-packages/django_statsd/patches/__init__.py:2: RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.
  from django.utils.importlib import import_module

Performing system checks...

System check identified no issues (0 silenced).
June 04, 2015 - 19:35:39
Django version 1.8.1, using settings 'auth.settings'
Starting development server at http://0.0.0.0:2603/
Quit the server with CONTROL-C.
[04/Jun/2015 19:48:07]"GET /v1/braintree/verify?bt_challenge=b6a82a50b550d92c9fb2 HTTP/1.1" 200 57
[04/Jun/2015 19:49:31]"POST /v1/braintree/parse HTTP/1.1" 204 0
[04/Jun/2015 19:49:46]"POST /v1/braintree/parse HTTP/1.1" 204 0
No local.py imported, skipping.
/opt/rh/python27/root/usr/lib/python2.7/site-packages/django_statsd/patches/__init__.py:2: RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.
  from django.utils.importlib import import_module

Performing system checks...

System check identified no issues (0 silenced).
June 04, 2015 - 19:50:34
Django version 1.8.1, using settings 'auth.settings'
Starting development server at http://0.0.0.0:2603/
Quit the server with CONTROL-C.
No handlers could be found for logger "auth.views"
[04/Jun/2015 19:50:39]"POST /v1/braintree/parse HTTP/1.1" 403 0
No local.py imported, skipping.
/opt/rh/python27/root/usr/lib/python2.7/site-packages/django_statsd/patches/__init__.py:2: RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.
  from django.utils.importlib import import_module

Performing system checks...

System check identified no issues (0 silenced).
June 04, 2015 - 19:51:00
Django version 1.8.1, using settings 'auth.settings'
Starting development server at http://0.0.0.0:2603/
Quit the server with CONTROL-C.
[04/Jun/2015 20:26:30]"POST /v1/braintree/parse HTTP/1.1" 204 0
[04/Jun/2015 20:26:55]"POST /v1/braintree/parse HTTP/1.1" 204 0
[04/Jun/2015 20:45:59]"POST /v1/braintree/parse HTTP/1.1" 204 0
[04/Jun/2015 20:45:59]"POST /v1/braintree/parse HTTP/1.1" 204 0
[04/Jun/2015 20:46:12]"POST /v1/braintree/parse HTTP/1.1" 204 0
[04/Jun/2015 20:46:12]"POST /v1/braintree/parse HTTP/1.1" 204 0
[04/Jun/2015 20:50:40]"POST /v1/braintree/parse HTTP/1.1" 204 0
[04/Jun/2015 20:51:09]"POST /v1/braintree/parse HTTP/1.1" 204 0
No local.py imported, skipping.
/opt/rh/python27/root/usr/lib/python2.7/site-packages/django_statsd/patches/__init__.py:2: RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.
  from django.utils.importlib import import_module

Performing system checks...

System check identified no issues (0 silenced).
June 04, 2015 - 20:58:15
Django version 1.8.1, using settings 'auth.settings'
Starting development server at http://0.0.0.0:2603/
Quit the server with CONTROL-C.
No local.py imported, skipping.
Performing system checks...

System check identified no issues (0 silenced).
CREATE TABLE "django_migrations" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "app" varchar(255) NOT NULL, "name" varchar(255) NOT NULL, "applied" datetime NOT NULL); (params None)
June 04, 2015 - 20:58:21
Django version 1.8.1, using settings 'auth.settings'
Starting development server at http://0.0.0.0:2603/
Quit the server with CONTROL-C.
Traceback (most recent call last):
  File "/srv/auth/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 303, in execute
    settings.INSTALLED_APPS
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/django/conf/__init__.py", line 48, in __getattr__
    self._setup(name)
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/django/conf/__init__.py", line 44, in _setup
    self._wrapped = Settings(settings_module)
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/django/conf/__init__.py", line 92, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/opt/rh/python27/root/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/srv/auth/auth/settings/__init__.py", line 1, in <module>
    from .base import *  # noqa
  File "/srv/auth/auth/settings/base.py", line 115
    <<<<<<< HEAD
     ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/srv/auth/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 303, in execute
    settings.INSTALLED_APPS
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/django/conf/__init__.py", line 48, in __getattr__
    self._setup(name)
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/django/conf/__init__.py", line 44, in _setup
    self._wrapped = Settings(settings_module)
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/django/conf/__init__.py", line 92, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/opt/rh/python27/root/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/srv/auth/auth/settings/__init__.py", line 1, in <module>
    from .base import *  # noqa
  File "/srv/auth/auth/settings/base.py", line 115
    <<<<<<< HEAD
     ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/srv/auth/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 303, in execute
    settings.INSTALLED_APPS
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/django/conf/__init__.py", line 48, in __getattr__
    self._setup(name)
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/django/conf/__init__.py", line 44, in _setup
    self._wrapped = Settings(settings_module)
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/django/conf/__init__.py", line 92, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/opt/rh/python27/root/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/srv/auth/auth/settings/__init__.py", line 1, in <module>
    from .base import *  # noqa
  File "/srv/auth/auth/settings/base.py", line 115
    <<<<<<< HEAD
     ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/srv/auth/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 303, in execute
    settings.INSTALLED_APPS
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/django/conf/__init__.py", line 48, in __getattr__
    self._setup(name)
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/django/conf/__init__.py", line 44, in _setup
    self._wrapped = Settings(settings_module)
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/django/conf/__init__.py", line 92, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/opt/rh/python27/root/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/srv/auth/auth/settings/__init__.py", line 1, in <module>
    from .base import *  # noqa
  File "/srv/auth/auth/settings/base.py", line 115
    <<<<<<< HEAD
     ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/srv/auth/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 303, in execute
    settings.INSTALLED_APPS
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/django/conf/__init__.py", line 48, in __getattr__
    self._setup(name)
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/django/conf/__init__.py", line 44, in _setup
    self._wrapped = Settings(settings_module)
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/django/conf/__init__.py", line 92, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/opt/rh/python27/root/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/srv/auth/auth/settings/__init__.py", line 1, in <module>
    from .base import *  # noqa
  File "/srv/auth/auth/settings/base.py", line 115
    <<<<<<< HEAD
     ^
SyntaxError: invalid syntax
